# 6CS012 - Worksheet 0 Solutions
### A Tutorial and Assessment on Python and NumPy for Deep Learning
---

## Section 4.1 — Task 1: Unit Converter

In [1]:
def convert_length(value, direction):
    """
    Converts length between meters and feet.
    Parameters:
        value (float): The numeric value to convert.
        direction (str): '1' for meters->feet, '2' for feet->meters.
    Returns:
        float: The converted value.
    """
    if direction == '1':
        result = value * 3.28084
        print(f"{value} meters = {result:.4f} feet")
    else:
        result = value / 3.28084
        print(f"{value} feet = {result:.4f} meters")
    return result

def convert_weight(value, direction):
    """
    Converts weight between kilograms and pounds.
    Parameters:
        value (float): The numeric value to convert.
        direction (str): '1' for kg->lbs, '2' for lbs->kg.
    Returns:
        float: The converted value.
    """
    if direction == '1':
        result = value * 2.20462
        print(f"{value} kg = {result:.4f} lbs")
    else:
        result = value / 2.20462
        print(f"{value} lbs = {result:.4f} kg")
    return result

def convert_volume(value, direction):
    """
    Converts volume between liters and gallons.
    Parameters:
        value (float): The numeric value to convert.
        direction (str): '1' for liters->gallons, '2' for gallons->liters.
    Returns:
        float: The converted value.
    """
    if direction == '1':
        result = value * 0.264172
        print(f"{value} L = {result:.4f} gal")
    else:
        result = value / 0.264172
        print(f"{value} gal = {result:.4f} L")
    return result

def unit_converter():
    """
    Prompts the user to select a conversion type and value,
    performs the conversion and displays the result.
    Returns:
        float or None: Converted value, or None on invalid input.
    """
    print("\n=== Unit Converter ===")
    print("Choose conversion category:")
    print("1. Length  (meters <-> feet)")
    print("2. Weight  (kg <-> lbs)")
    print("3. Volume  (liters <-> gallons)")
    category = input("Enter category (1/2/3): ").strip()
    if category not in ('1', '2', '3'):
        print("Invalid category.")
        return None
    direction_labels = {
        '1': ("meters -> feet", "feet -> meters"),
        '2': ("kg -> lbs",      "lbs -> kg"),
        '3': ("liters -> gal",  "gal -> liters"),
    }
    labels = direction_labels[category]
    print(f"\nChoose direction:\n1. {labels[0]}\n2. {labels[1]}")
    direction = input("Enter direction (1/2): ").strip()
    if direction not in ('1', '2'):
        print("Invalid direction.")
        return None
    try:
        value = float(input("Enter the value to convert: "))
    except ValueError:
        print("Invalid input: please enter a numeric value.")
        return None
    converters = {'1': convert_length, '2': convert_weight, '3': convert_volume}
    return converters[category](value, direction)

unit_converter()


=== Unit Converter ===
Choose conversion category:
1. Length  (meters <-> feet)
2. Weight  (kg <-> lbs)
3. Volume  (liters <-> gallons)
Enter category (1/2/3): 2

Choose direction:
1. kg -> lbs
2. lbs -> kg
Enter direction (1/2): 1
Enter the value to convert: 5
5.0 kg = 11.0231 lbs


11.0231

## Section 4.1 — Task 2: Math Operations on a List

In [2]:
def compute_sum(numbers):
    """
    Returns the sum of a list of numbers.
    Parameters:
        numbers (list of float): Input numbers.
    Returns:
        float: Sum of all elements.
    """
    if not numbers:
        raise ValueError("The list is empty.")
    total = 0
    for n in numbers:
        total += n
    return total

def compute_average(numbers):
    """
    Returns the average of a list of numbers.
    Parameters:
        numbers (list of float): Input numbers.
    Returns:
        float: Mean of all elements.
    """
    if not numbers:
        raise ValueError("The list is empty.")
    return compute_sum(numbers) / len(numbers)

def compute_maximum(numbers):
    """
    Returns the maximum value in a list of numbers.
    Parameters:
        numbers (list of float): Input numbers.
    Returns:
        float: The largest element.
    """
    if not numbers:
        raise ValueError("The list is empty.")
    max_val = numbers[0]
    for n in numbers[1:]:
        if n > max_val:
            max_val = n
    return max_val

def compute_minimum(numbers):
    """
    Returns the minimum value in a list of numbers.
    Parameters:
        numbers (list of float): Input numbers.
    Returns:
        float: The smallest element.
    """
    if not numbers:
        raise ValueError("The list is empty.")
    min_val = numbers[0]
    for n in numbers[1:]:
        if n < min_val:
            min_val = n
    return min_val

def math_operations():
    """
    Prompts the user to select an operation and provide a list of numbers,
    then computes and displays the result.
    Returns:
        float or None: Result of the operation, or None on invalid input.
    """
    print("\n=== Math Operations ===")
    print("1. Sum\n2. Average\n3. Maximum\n4. Minimum")
    choice = input("Choose operation (1-4): ").strip()
    if choice not in ('1', '2', '3', '4'):
        print("Invalid choice.")
        return None
    raw = input("Enter numbers separated by spaces: ")
    try:
        numbers = [float(x) for x in raw.split()]
        if not numbers:
            raise ValueError("No numbers provided.")
    except ValueError as e:
        print(f"Invalid input: {e}")
        return None
    ops = {'1': compute_sum, '2': compute_average,
           '3': compute_maximum, '4': compute_minimum}
    try:
        result = ops[choice](numbers)
        print(f"Result: {result}")
        return result
    except ValueError as e:
        print(f"Error: {e}")
        return None

math_operations()


=== Math Operations ===
1. Sum
2. Average
3. Maximum
4. Minimum
Choose operation (1-4): 1
Enter numbers separated by spaces: 3 7 2 9 1 5
Result: 27.0


27.0

---
## Section 4.2 — List Manipulation

In [3]:
# 1. Extract every other element
def extract_every_other(lst):
    """Returns every other element starting from index 0."""
    return lst[::2]

raw = input("1. Enter numbers separated by spaces: ")
lst = [int(x) for x in raw.split()]
print("Every other element:", extract_every_other(lst))

1. Enter numbers separated by spaces: 1 2 3 4 5 6
Every other element: [1, 3, 5]


In [4]:
# 2. Slice a sublist
def get_sublist(lst, start, end):
    """Returns elements from index start to end (inclusive)."""
    return lst[start:end + 1]

raw   = input("2. Enter numbers separated by spaces: ")
lst   = [int(x) for x in raw.split()]
start = int(input("   Enter start index: "))
end   = int(input("   Enter end index: "))
print("Sublist:", get_sublist(lst, start, end))

2. Enter numbers separated by spaces: 1 2 3 4 5 6
   Enter start index: 2
   Enter end index: 4
Sublist: [3, 4, 5]


In [5]:
# 3. Reverse a list using slicing
def reverse_list(lst):
    """Returns the list in reversed order using slicing."""
    return lst[::-1]

raw = input("3. Enter numbers separated by spaces: ")
lst = [int(x) for x in raw.split()]
print("Reversed list:", reverse_list(lst))

3. Enter numbers separated by spaces: 1 2 3 4 5
Reversed list: [5, 4, 3, 2, 1]


In [6]:
# 4. Remove first and last elements
def remove_first_last(lst):
    """Returns the list without its first and last elements."""
    return lst[1:-1]

raw = input("4. Enter numbers separated by spaces: ")
lst = [int(x) for x in raw.split()]
print("After removing first and last:", remove_first_last(lst))

4. Enter numbers separated by spaces: 1 2 3 4 5
After removing first and last: [2, 3, 4]


In [7]:
# 5. Get first n elements
def get_first_n(lst, n):
    """Returns the first n elements of the list."""
    return lst[:n]

raw = input("5. Enter numbers separated by spaces: ")
lst = [int(x) for x in raw.split()]
n   = int(input("   Enter n: "))
print(f"First {n} elements:", get_first_n(lst, n))

5. Enter numbers separated by spaces: 1 2 3 4 5
   Enter n: 3
First 3 elements: [1, 2, 3]


In [8]:
# 6. Extract last n elements
def get_last_n(lst, n):
    """Returns the last n elements of the list."""
    return lst[-n:]

raw = input("6. Enter numbers separated by spaces: ")
lst = [int(x) for x in raw.split()]
n   = int(input("   Enter n: "))
print(f"Last {n} elements:", get_last_n(lst, n))

6. Enter numbers separated by spaces: 1 2 3 4 5
   Enter n: 2
Last 2 elements: [4, 5]


In [9]:
# 7. Reverse skip
def reverse_skip(lst):
    """Returns every second element starting from the second-to-last, moving backward."""
    return lst[-2::-2]

raw = input("7. Enter numbers separated by spaces: ")
lst = [int(x) for x in raw.split()]
print("Reverse skip result:", reverse_skip(lst))

7. Enter numbers separated by spaces: 1 2 3 4 5 6
Reverse skip result: [5, 3, 1]


---
## Section 4.3 — Nested Lists

In [12]:
# 1. Flatten a nested list
def flatten(lst):
    """Flattens a one-level nested list into a single list."""
    result = []
    for sublist in lst:
        for item in sublist:
            result.append(item)
    return result

print("1. Enter sublists one per line (e.g. 1 2 3). Blank line to finish:")
nested = []
while True:
    row = input()
    if row.strip() == '':
        break
    nested.append([int(x) for x in row.split()])
print("Flattened:", flatten(nested))

1. Enter sublists one per line (e.g. 1 2 3). Blank line to finish:
12
34
5

Flattened: [12, 34, 5]


In [16]:
# 2. Access nested element by indices
def access_nested_element(lst, indices):
    """Returns the element at the position described by the indices list."""
    element = lst
    for idx in indices:
        element = element[idx]
    return element

print("2. Enter sublists one per line. Blank line to finish:")
nested = []
while True:
    row = input()
    if row.strip() == '':
        break
    nested.append([int(x) for x in row.split()])
raw_idx = input("Enter indices separated by spaces (e.g. 1 2): ")
indices = [int(x) for x in raw_idx.split()]
print("Element at", indices, ":", access_nested_element(nested, indices))

2. Enter sublists one per line. Blank line to finish:
11
22
44

Enter indices separated by spaces (e.g. 1 2): 1
Element at [1] : [22]


In [17]:
4# 3. Sum of all elements
def sum_nested(lst):
    """Recursively sums all numeric elements in a nested list."""
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)
        else:
            total += item
    return total

print("3. Enter sublists one per line. Blank line to finish:")
nested = []
while True:
    row = input()
    if row.strip() == '':
        break
    nested.append([int(x) for x in row.split()])
print("Sum of all elements:", sum_nested(nested))

3. Enter sublists one per line. Blank line to finish:
22
33

Sum of all elements: 55


In [21]:
# 4. Remove specific element
def remove_element(lst, elem):
    """Removes all occurrences of elem from each sub-list."""
    return [[x for x in sublist if x != elem] for sublist in lst]

print("4. Enter sublists one per line. Blank line to finish:")
nested = []
while True:
    row = input()
    if row.strip() == '':
        break
    nested.append([int(x) for x in row.split()])
elem = int(input("Enter element to remove: "))
print("After removal:", remove_element(nested, elem))

4. Enter sublists one per line. Blank line to finish:
1 2
3 2
4 5

Enter element to remove: 2
After removal: [[1], [3], [4, 5]]


In [22]:
# 5. Find maximum element
def find_max(lst):
    """Recursively finds the maximum element in a nested list."""
    max_val = None
    for item in lst:
        candidate = find_max(item) if isinstance(item, list) else item
        if max_val is None or candidate > max_val:
            max_val = candidate
    return max_val

print("5. Enter sublists one per line. Blank line to finish:")
nested = []
while True:
    row = input()
    if row.strip() == '':
        break
    nested.append([int(x) for x in row.split()])
print("Maximum element:", find_max(nested))

5. Enter sublists one per line. Blank line to finish:
1 2 3
1 2
3 3

Maximum element: 3


In [23]:
# 6. Count occurrences
def count_occurrences(lst, elem):
    """Recursively counts occurrences of elem in a nested list."""
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        elif item == elem:
            count += 1
    return count

print("6. Enter sublists one per line. Blank line to finish:")
nested = []
while True:
    row = input()
    if row.strip() == '':
        break
    nested.append([int(x) for x in row.split()])
elem = int(input("Enter element to count: "))
print(f"'{elem}' appears", count_occurrences(nested, elem), "time(s)")

6. Enter sublists one per line. Blank line to finish:
11 1
2 2
3 3

Enter element to count: 2
'2' appears 2 time(s)


In [24]:
# 7. Deep flatten
def deep_flatten(lst):
    """Recursively flattens a deeply nested list into a single flat list."""
    result = []
    for item in lst:
        if isinstance(item, list):
            result.extend(deep_flatten(item))
        else:
            result.append(item)
    return result

print("7. Enter sublists one per line. Blank line to finish:")
nested = []
while True:
    row = input()
    if row.strip() == '':
        break
    nested.append([int(x) for x in row.split()])
print("Deep flattened:", deep_flatten(nested))

7. Enter sublists one per line. Blank line to finish:
1 1
2 3
3 2
4 5

Deep flattened: [1, 1, 2, 3, 3, 2, 4, 5]


In [25]:
# 8. Average of nested list
def average_nested(lst):
    """Returns the average of all numeric elements in a nested list."""
    all_elements = deep_flatten(lst)
    return sum(all_elements) / len(all_elements)

print("8. Enter sublists one per line. Blank line to finish:")
nested = []
while True:
    row = input()
    if row.strip() == '':
        break
    nested.append([int(x) for x in row.split()])
print("Average of all elements:", average_nested(nested))

8. Enter sublists one per line. Blank line to finish:
1 2 3
4 5 6
2 2
1 1

Average of all elements: 2.7


---
## Section 10.1 — Problem 1: Array Creation

In [26]:
import numpy as np

# 1. Empty 2x2
print("1. Empty 2x2:\n", np.empty((2, 2)))

# 2. Ones 4x2
print("\n2. Ones 4x2:\n", np.ones((4, 2)))

# 3. np.full — user provides shape and fill value
rows = int(input("\n3. Rows for np.full: "))
cols = int(input("   Cols for np.full: "))
fval = float(input("   Fill value: "))
print(f"   np.full({rows}x{cols}, {fval}):\n", np.full((rows, cols), fval))

# 4 & 5. zeros_like / ones_like — user provides reference array
print("\n4 & 5. Enter reference array row by row. Blank line to finish:")
ref_data = []
while True:
    row = input()
    if row.strip() == '':
        break
    ref_data.append([float(x) for x in row.split()])
reference = np.array(ref_data)
print("zeros_like:\n", np.zeros_like(reference))
print("ones_like:\n",  np.ones_like(reference))

# 6. Convert user list to numpy array
raw = input("\n6. Enter numbers to convert to numpy array: ")
print("Array:", np.array([float(x) for x in raw.split()]))

1. Empty 2x2:
 [[1.85525661e-315 0.00000000e+000]
 [9.88131292e-324             nan]]

2. Ones 4x2:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

3. Rows for np.full: 3
   Cols for np.full: 3
   Fill value: 7
   np.full(3x3, 7.0):
 [[7. 7. 7.]
 [7. 7. 7.]
 [7. 7. 7.]]

4 & 5. Enter reference array row by row. Blank line to finish:
1 2 3
4 5 7

zeros_like:
 [[0. 0. 0.]
 [0. 0. 0.]]
ones_like:
 [[1. 1. 1.]
 [1. 1. 1.]]

6. Enter numbers to convert to numpy array: 1 2 3 4
Array: [1. 2. 3. 4.]


## Section 10.1 — Problem 2: Array Manipulation

In [27]:
import numpy as np

print("1. arange 10-49:\n", np.arange(10, 50))
print("\n2. 3x3 matrix (0-8):\n", np.arange(9).reshape(3, 3))
print("\n3. Identity 3x3:\n", np.eye(3))

rand_arr = np.random.random(30)
print("\n4. Random array (size 30):", rand_arr)
print("   Mean:", rand_arr.mean())

rand_10x10 = np.random.random((10, 10))
print("\n5. 10x10 random -> min:", rand_10x10.min(), "| max:", rand_10x10.max())

z = np.zeros(10); z[4] = 1
print("\n6. Zero array with 5th element = 1:\n", z)

# 7. User provides array to reverse
raw = input("\n7. Enter array elements to reverse (space-separated): ")
arr = np.array([int(x) for x in raw.split()])
print("   Reversed:", arr[::-1])

# 8. User provides size for border array
size = int(input("\n8. Enter size n for n x n border array: "))
border = np.ones((size, size))
border[1:-1, 1:-1] = 0
print(f"   {size}x{size} border array:\n", border)

cb = np.zeros((8, 8), dtype=int)
cb[1::2, ::2] = 1
cb[::2, 1::2] = 1
print("\n9. 8x8 Checkerboard:\n", cb)

1. arange 10-49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

2. 3x3 matrix (0-8):
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3. Identity 3x3:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

4. Random array (size 30): [0.92457636 0.01559177 0.57090887 0.33034447 0.75525385 0.70657064
 0.10819543 0.20521645 0.00580173 0.24659536 0.3668492  0.95115576
 0.68751639 0.99387532 0.20141552 0.62739287 0.16422799 0.20797785
 0.39841677 0.09587285 0.35859695 0.58913514 0.65506763 0.04145487
 0.25889612 0.10858181 0.03970626 0.63255516 0.83554219 0.44170514]
   Mean: 0.4174998898918631

5. 10x10 random -> min: 0.015806917290112743 | max: 0.9921348042072735

6. Zero array with 5th element = 1:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

7. Enter array elements to reverse (space-separated): 1 2 0 0 4 0
   Reversed: [0 4 0 0 2 1]

8. Enter size n for n x n border array: 6
   6x6 border array:
 [[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 

## Section 10.1 — Problem 3: Array Operations

In [28]:
import numpy as np

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

print("1. x + y =\n", x + y)
print("\n2. x - y =\n", x - y)

scalar = int(input("\n3. Enter an integer to multiply the array x by: "))
print(f"   x * {scalar} =\n", x * scalar)

print("\n4. Square of each element of x =\n", np.square(x))
print("\n5a. dot(v, w)  =", np.dot(v, w))
print("5b. dot(x, v)  =", np.dot(x, v))
print("5c. dot(x, y)  =\n", np.dot(x, y))

print("\n6a. Concatenate x and y along rows:\n",
      np.concatenate((x, y), axis=0))
print("6b. Concatenate v and w (as column vectors):\n",
      np.concatenate((v.reshape(1, -1), w.reshape(1, -1)), axis=0))

print("\n7. Trying np.concatenate(x, v):")
try:
    np.concatenate((x, v))
except ValueError as e:
    print(f"   Error: {e}")
    print("   Reason: x is 2D (shape 2x2) but v is 1D (shape 2,).")
    print("   np.concatenate requires all arrays to have the same number of dimensions.")
    print("   Fix: reshape v to (1, 2) first.")
    print("   Fixed result:\n", np.concatenate((x, v.reshape(1, 2)), axis=0))

1. x + y =
 [[ 6  8]
 [10 13]]

2. x - y =
 [[-4 -4]
 [-4 -3]]

3. Enter an integer to multiply the array x by: 3
   x * 3 =
 [[ 3  6]
 [ 9 15]]

4. Square of each element of x =
 [[ 1  4]
 [ 9 25]]

5a. dot(v, w)  = 219
5b. dot(x, v)  = [29 77]
5c. dot(x, y)  =
 [[19 22]
 [50 58]]

6a. Concatenate x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
6b. Concatenate v and w (as column vectors):
 [[ 9 10]
 [11 12]]

7. Trying np.concatenate(x, v):
   Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
   Reason: x is 2D (shape 2x2) but v is 1D (shape 2,).
   np.concatenate requires all arrays to have the same number of dimensions.
   Fix: reshape v to (1, 2) first.
   Fixed result:
 [[ 1  2]
 [ 3  5]
 [ 9 10]]


## Section 10.1 — Problem 4: Matrix Operations

In [29]:
import numpy as np

A = np.array([[3, 4], [7, 8]], dtype=float)
B = np.array([[5, 3], [2, 1]], dtype=float)

print("1. A * A_inv (should be Identity):\n",
      np.round(np.dot(A, np.linalg.inv(A)), 10))

AB = np.dot(A, B)
BA = np.dot(B, A)
print("\n2a. AB =\n", AB)
print("2b. BA =\n", BA)
print("   AB == BA?", np.allclose(AB, BA))

print("\n3a. (AB)^T =\n", AB.T)
print("3b. B^T * A^T =\n", np.dot(B.T, A.T))
print("   Equal?", np.allclose(AB.T, np.dot(B.T, A.T)))

coeff    = np.array([[ 2, -3,  1],
                     [ 1, -1,  2],
                     [ 3,  1, -1]], dtype=float)
constants = np.array([-1, -3, 9], dtype=float)

print("\n--- Solving:  2x-3y+z=-1 | x-y+2z=-3 | 3x+y-z=9 ---")
X_inv   = np.dot(np.linalg.inv(coeff), constants)
X_solve = np.linalg.solve(coeff, constants)
print("Method 1 (A_inv * B):    x={:.4f}, y={:.4f}, z={:.4f}".format(*X_inv))
print("Method 2 (linalg.solve): x={:.4f}, y={:.4f}, z={:.4f}".format(*X_solve))
print("Verification AX =>", np.round(np.dot(coeff, X_solve), 6))

1. A * A_inv (should be Identity):
 [[1. 0.]
 [0. 1.]]

2a. AB =
 [[23. 13.]
 [51. 29.]]
2b. BA =
 [[36. 44.]
 [13. 16.]]
   AB == BA? False

3a. (AB)^T =
 [[23. 51.]
 [13. 29.]]
3b. B^T * A^T =
 [[23. 51.]
 [13. 29.]]
   Equal? True

--- Solving:  2x-3y+z=-1 | x-y+2z=-3 | 3x+y-z=9 ---
Method 1 (A_inv * B):    x=2.0000, y=1.0000, z=-2.0000
Method 2 (linalg.solve): x=2.0000, y=1.0000, z=-2.0000
Verification AX => [-1. -3.  9.]


---
## Section 10.2 — How Fast is NumPy?

In [30]:
import numpy as np
import time

SIZE = 1_000_000

def speedup_msg(loop_t, np_t):
    print(f"  Python loop : {loop_t:.5f}s")
    print(f"  NumPy       : {np_t:.5f}s")
    print(f"  Speedup     : {loop_t / np_t:.1f}x faster\n")

# 1. Element-wise Addition
print("=" * 50)
print("1. Element-wise Addition (size 1,000,000)")
a_list = list(range(SIZE)); b_list = list(range(SIZE))
t0 = time.time()
_ = [a_list[i] + b_list[i] for i in range(SIZE)]
loop_add = time.time() - t0
a_np = np.array(a_list); b_np = np.array(b_list)
t0 = time.time()
_ = a_np + b_np
speedup_msg(loop_add, time.time() - t0)

# 2. Element-wise Multiplication
print("2. Element-wise Multiplication (size 1,000,000)")
t0 = time.time()
_ = [a_list[i] * b_list[i] for i in range(SIZE)]
loop_mul = time.time() - t0
t0 = time.time()
_ = a_np * b_np
speedup_msg(loop_mul, time.time() - t0)

# 3. Dot Product
print("3. Dot Product (size 1,000,000)")
t0 = time.time()
_ = sum(a_list[i] * b_list[i] for i in range(SIZE))
loop_dot = time.time() - t0
t0 = time.time()
_ = np.dot(a_np, b_np)
speedup_msg(loop_dot, time.time() - t0)

# 4. Matrix Multiplication 1000x1000
print("4. Matrix Multiplication (1000x1000)")
MAT = 1000
m1 = [[float(i*MAT+j) for j in range(MAT)] for i in range(MAT)]
m2 = [[float(i*MAT+j) for j in range(MAT)] for i in range(MAT)]
t0 = time.time()
_ = [[sum(m1[i][k]*m2[k][j] for k in range(MAT)) for j in range(MAT)] for i in range(MAT)]
loop_mat = time.time() - t0
m1_np = np.array(m1); m2_np = np.array(m2)
t0 = time.time()
_ = np.dot(m1_np, m2_np)
speedup_msg(loop_mat, time.time() - t0)

1. Element-wise Addition (size 1,000,000)
  Python loop : 0.13879s
  NumPy       : 0.01949s
  Speedup     : 7.1x faster

2. Element-wise Multiplication (size 1,000,000)
  Python loop : 0.10873s
  NumPy       : 0.01708s
  Speedup     : 6.4x faster

3. Dot Product (size 1,000,000)
  Python loop : 0.11088s
  NumPy       : 0.00194s
  Speedup     : 57.2x faster

4. Matrix Multiplication (1000x1000)
  Python loop : 99.68870s
  NumPy       : 0.06112s
  Speedup     : 1631.0x faster

